FROM nginx:alpine

# Удаляем стандартный конфиг Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Копируем наш новый конфиг
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Копируем сайт
COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80