# Этап 1: Сборка
FROM node:18-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install

# --- МАГИЯ ZДЕСЬ ---
# Объявляем, что мы ждем аргумент VITE_BACKEND_URL
ARG VITE_BACKEND_URL
# Превращаем его в переменную окружения, чтобы Vite его увидел
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
# -------------------

COPY . .
RUN npm run build

# Этап 2: Запуск
FROM nginx:alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]